name: exitplan
version: '3.8'

services:
  nodejs:
    image: node:16
    container_name: nodejs-server
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:80"
    command: sh -c "npm install && nodemon server.js"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: