name: exitplan
version: '3.8'

services:
  nodejs:
    image: node:latest
    container_name: nodejs-server
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    command: sh -c "npm install && nodemon server.js"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/exitplan

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: